+++
title = "Known System Related Issues"
summary = "Known system related issues with KiCad on various platforms"
aliases = [ "/post/known-system-related-issues/" ]
[menu.main]
    parent = "Help"
    name   = "Known System Related Issues"
  weight = 50
+++
:toc: macro
:toc-title:

toc::[]

This page is just a small note on some "weird" issues that have been
experienced with KiCad in relation to the systems that it runs on. This
means that this page does not describe KiCad functional bugs.

== All Platforms

=== High DPI Screens

KiCad is configured to automatically detect the proper scaling factor for
displaying the editor canvas on the screen by default. If the canvas only uses
1/4 of the screen and there is a constant offset between the cursor and
crosshairs, check to ensure that automatic canvas scaling is enabled on the
common settings page of the Preferences dialog.

There are some known issues that can cause the canvas to not automatically scale
properly, primarily on Linux installations (see https://bugs.launchpad.net/kicad/+bug/1841423[Launchpad Bug #1841423]
and https://gitlab.com/kicad/code/kicad/issues/54[GitLab Bug #54]).
To fix this, disable the automatic canvas scaling in the preferences
window and enter a custom scale factor. In most cases a scaling factor
of 2 seems to fix the issue.

Toolbar icons may also appear smaller on high DPI screens, but their size
can be scaled in the preferences window as well.

Menu items may have inconsistent vertical sizing, causing the bottom part of
the text to be cutoff. Disabling "Show icons in menus" in the Preferences
dialog will make all menu items a uniform height and fix the cutoff text
(see https://gitlab.com/kicad/code/kicad/issues/3785[GitLab Bug #3785]).

The grid dots may be difficult to see due to their smaller size on
these displays. On the modern canvas, their size can be increased
in the preferences window (see https://gitlab.com/kicad/code/kicad/issues/444[GitLab Bug #444]).


== Linux-Specific Issues

=== Radeon Graphics

Some users with Radeon graphics have been experiencing problems with
slow rendering in gerbview and eeschema.
https://bugs.launchpad.net/kicad/+bug/1003859[Some]
https://bugs.launchpad.net/kicad/+bug/1186813[bugs] have been opened related to Radeon cards.
The solution seems to be require changing an Xorg setting which is either `Option "EXAPixmaps" "off"` or `Option "ShadowPrimary"` (see the bug reports for details).

=== Wayland
It is known that KiCad does not work well under Wayland. There are a number
of known issues with wxWidgets and Wayland.  link:https://trac.wxwidgets.org/query?status=!closed&keywords=~Wayland[See the wxWidgets bug tracker for details].

KiCad requests the XWayland compatibility layer when starting, however this is
an emulation mode and issues arising while using this mode need to be recreated
under X11 before they will be addressed.

=== MATE

Some versions of MATE (on Ubuntu or Linux Mint) together with GTK3 and wxWidgets can lead to rendering problems
and keyboard keys that do not work or can freeze the GUI input. They are potentially caused
by the ibus. To solve it, install the packages ibus-gtk and ibus-gtk3, and restart the computer (or log out).
Alternatively, you can quit the ibus calling in a terminal 'ibus exit' before starting KiCad.  
More details can be found in link:https://gitlab.com/kicad/code/kicad/-/issues/4547[GitLab Bug# 4547].

